// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFh1OSIzXrTdmm4H_fzQIa1mrF8H3clnc',
    appId: '1:554788460660:web:798e221c1950fef5f19921',
    messagingSenderId: '554788460660',
    projectId: 'food-management-app-ff8df',
    authDomain: 'food-management-app-ff8df.firebaseapp.com',
    storageBucket: 'food-management-app-ff8df.firebasestorage.app',
    measurementId: 'G-7ZVQXRENP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfEt8P9-s8gY5g-MSOvMh9nT99jH3GVXk',
    appId: '1:554788460660:android:87c8baf0ab90031bf19921',
    messagingSenderId: '554788460660',
    projectId: 'food-management-app-ff8df',
    storageBucket: 'food-management-app-ff8df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBREkubkxJXKG7zyPl1FHi-eDtn7hoKg30',
    appId: '1:554788460660:ios:7cea3c9d13b767d4f19921',
    messagingSenderId: '554788460660',
    projectId: 'food-management-app-ff8df',
    storageBucket: 'food-management-app-ff8df.firebasestorage.app',
    iosBundleId: 'com.example.foodManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBREkubkxJXKG7zyPl1FHi-eDtn7hoKg30',
    appId: '1:554788460660:ios:7cea3c9d13b767d4f19921',
    messagingSenderId: '554788460660',
    projectId: 'food-management-app-ff8df',
    storageBucket: 'food-management-app-ff8df.firebasestorage.app',
    iosBundleId: 'com.example.foodManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFh1OSIzXrTdmm4H_fzQIa1mrF8H3clnc',
    appId: '1:554788460660:web:fcd1f80c1dc49686f19921',
    messagingSenderId: '554788460660',
    projectId: 'food-management-app-ff8df',
    authDomain: 'food-management-app-ff8df.firebaseapp.com',
    storageBucket: 'food-management-app-ff8df.firebasestorage.app',
    measurementId: 'G-57BJK4FMKB',
  );
}
